### ISSUE TITLE
How do we decide if a dataset should be stored in sparse format or not  ?

### ISSUE THREAD

**Issue by mathurinm** [mathurinm/libsvmdata#21]
The X data returned by `load_svm_light` is always a sparse CSC matrix, that we cast to dense if `len(X.data) == X.shape[1] * X.shape[0]`

This means that datasets such as gisette, which are dense, are stored as CSC, since they have a few zeros:
```python
In [7]: X, y = libsvmdata.fetch_libsvm("gisette")
Dataset: gisette

In [8]: X
Out[8]: 
<6000x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 29729997 stored elements in Compressed Sparse Column format>

In [9]: len(X.data) / X.shape[0] / X.shape[1]
Out[9]: 0.99
```

should use a threshold density to cast to dense ? which value ?
@agramfort

**Comment by mathurinm** [comment]
We could use sparse format only if density is <= 0.5 (nnz = 0.5 n * p) , since the storage cost of CSC is 2 * NNZ + p  while the dense storage cost is n * p

Sounds ok @agramfort  ?

**Comment by agramfort** [comment]
I like that idea !

>
