### ISSUE TITLE
CLN change default directory for the data

### ISSUE THREAD

**Issue by tomMoral** [mathurinm/libsvmdata#4]
The default directory is `$HOME/libsvm_data`. This add a directory in `$HOME` which is not hidden.

Making the default directory `$HOME/.data/libsvm` would be much better in my opinion.

**Comment by agramfort** [comment]
I would not hide this.

it can create files of more than 3GB and I anticipate that it silently
fills the homes on dragos for example

**Comment by mathurinm** [comment]
Maybe a good compromise is to leave it as is by default, but allow the user to specify a value in a config file ? I had this in mind, but did not investigate further

**Comment by tomMoral** [comment]
Having X `*_data` folders in `$HOME` is very annoying. It makes `ls` way to verbose in a directory that is used every day.

At least putting it in a folder such as `data/libsvm` (not hidden) that could be shared to store every data folder would be awesome.

I would say that hidding it is better but this is personnal preference.  
I agree that having a possible config file would be awesome but it is more than the usual trotinette ;).

**Comment by agramfort** [comment]
I can live with sklearn_data libsvm_data mne_data in my home.

I need to choose my battles....

>

**Comment by tomMoral** [comment]
I would live much better without and I don't see a good reason to not do
this.

**Comment by agramfort** [comment]
I respect your battle choices :)

>
